# Generated by Django 4.2.5 on 2023-09-22 17:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_ingredient_options_dish_slogan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Завтрак')),
                ('dinner', models.BooleanField(default=False, verbose_name='Ужин')),
                ('lunch', models.BooleanField(default=False, verbose_name='Обед')),
                ('dessert', models.BooleanField(default=False, verbose_name='Десерты')),
                ('people_count', models.IntegerField(default=1, verbose_name='Кол-во людей')),
                ('month_count', models.IntegerField(default=1, verbose_name='Кол-во месяцев')),
                ('paid', models.BooleanField(default=False, verbose_name='оплачено')),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма заказа')),
                ('intolerance', models.ManyToManyField(related_name='orders', to='foods.foodintolerance')),
            ],
        ),
    ]
