# Generated by Django 4.2.5 on 2023-09-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('foods', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='foods.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы клиентов',
            },
        ),
    ]
