# Generated by Django 4.2.5 on 2023-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(default=0, max_length=64, verbose_name='yookassa id'),
            preserve_default=False,
        ),
    ]
