name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: build and run  
      run: |
        docker build . --file Dockerfile --tag food:develop
        --env=SECRET_KEY=12345 \
        --env=ALLOWED_HOSTS=82.148.31.19 \
        --env=DEBUG=True \
        --env=ACCOUNT_ID=237136 \
        --env=U_KEY='test_8veJnrLUb09Z9rU5B_kFryjyJwDfiThi8cI926tTxN0' \
    - name:  run 
      run: |
        docker kill food || true; \
        docker run -d -p 80:8000 --rm --name food \
        --env=SECRET_KEY=12345 \
        --env=ALLOWED_HOSTS=82.148.31.19 \
        --env=DEBUG=True \
        --env=ACCOUNT_ID=237136 \
        --env=U_KEY='test_8veJnrLUb09Z9rU5B_kFryjyJwDfiThi8cI926tTxN0' \
        food:develop
